### ISSUE TITLE
[bug] 'prevent sleep' not disabling after enabled by other activity

### ISSUE THREAD

**Issue by denniedegroot** [unfoldedcircle/bug-reports#326] opened 2024-02-19 11:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have 3 activities of which 1 has the 'prevent sleep' option enabled. When selecting this activity and switch to a other activity the remote doesn't sleep again and the 'prevent sleep' is enabled for all activities until the remote is rebooted again.

### How to Reproduce

1. Create 2 activities, 1 with prevent sleep and 1 without.
2. Start activity 1 and then start activity 2 (without prevent sleep).
3. The remote doesn't go to sleep mode.

### Expected behavior

I expect the remote to sleep when prevent sleep is disabled in my activity.

### System version

1.6.10

### What part of the system affected by the problem?

Core

**Comment by denniedegroot** [comment] 2024-02-19 12:10
#281 might be related.

**Comment by zehnm** [comment] 2024-03-25 19:46
Confirmed: caused by same bug as #281 and fixed in next release.
Already available in BETA channel: v1.7.8

**Comment by zehnm** [comment] 2024-05-16 15:18
Fixed in release 1.7.12

**Closed as completed by zehnm** 2024-05-16 15:18 UTC
Labels: bug, core
