### ISSUE TITLE
[bug] Can not use "/" character in IR button name

### ISSUE THREAD

**Issue by bikeymouse** [unfoldedcircle/bug-reports#187] opened 2023-11-11 16:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If want to create a new remote button that has a name containing the "/" character, I can not save the button with the IR code.
The interface responds with a "bad request" and gives no indication what is wrong.
<img width="937" alt="slash-button" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/34967010/454e9295-dab2-48cb-81e9-122146079a0f">

### How to Reproduce

1. Goto webconfig
2. Click remotes
3. Select remote
4. Click pen-symbol on IR-data set
5. Add a new name with a "/" in the box besides the "custom button" button
6. Add an IR code or learn IR-code
7. Click save

### Expected behavior

Button should be saved or a proper error-resonse indicating what's wrong should be given.

### System version

1.4.5

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment] 2023-11-29 11:09
Confirmed, a `/` character in the button name doesn't work for learning IR commands. This will be fixed in the next release.

The issue is only present on the remote device because of the reverse proxy. It decodes all encoded URLs by default and the reason we didn't caught it during development. Since the encoded IR command name is used in the URL as parameter, this then calls an unknown service endpoint. Instead of `/api/remotes/:entityId/ir/test%2Ftest` this was sent to the service: `/api/remotes/:entityId/ir/test/test`.

**Comment by zehnm** [comment] 2023-12-01 13:07
Included in BETA release group and soon available.

**Comment by zehnm** [comment] 2023-12-14 14:41
Fixed in v1.5.2

**Closed as completed by zehnm** 2023-12-14 14:41 UTC
Labels: bug, web configurator, ir
