### ISSUE TITLE
[bug] Display correct volume values

### ISSUE THREAD

**Issue by alexthegreat100** [unfoldedcircle/bug-reports#308] opened 2024-02-05 21:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the volume is adjusted by pressing the volume buttons on the remote control during an activity with an AppleTV, a numerical volume UI appears on the remote control display.
However, the UI does not show the actual volume of the controlled device (e.g. -40 dB or simply 40). The UI remains at the value 50 and does not change at all.

https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/150591634/0ad79f03-b099-4c4d-81b9-242b71e07d02

### How to Reproduce

1. Start an Activity with AppleTV
2. Press Vol+/- on the Remote

### Expected behavior

Either the volume is no longer shown or it shows the correct value.

### System version

1.6.7

### What part of the system affected by the problem?

UI

**Comment by kennymc-c** [comment] 2024-02-05 23:13
If the volume buttons are mapped to the Apple TV itself this seems to be a duplicate of https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/10

**Comment by martonborzak** [comment] 2024-02-07 11:33
Duplicate of #10

**Closed as completed by martonborzak** 2024-02-07 11:33 UTC
Labels: bug, ui

**Comment by alexthegreat100** [comment] 2024-02-07 11:36
Sorry! Thanks for closing it. 🥇
