### ISSUE TITLE
[bug] Profile selection shows two empty profiles that can't be selected

### ISSUE THREAD

**Issue by F4Ck0R** [unfoldedcircle/bug-reports#115] opened 2023-10-08 11:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have configured one Profile named "Michael" (I left it default during initial setup and renamed it afterwards). When I navigate to the Profiles page in the Web ui and try to select one of the showed profiles it looks like this:

![Screenshot 2023-10-08 125341](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/111465037/f71f68c1-6434-4c14-ae51-1a2fe8e535be)

BTW: It first didn't work, the it worked and I saw only my profile and now I'm back stuck with two empty Profiles again. As workaround I currently use the remotes local UI with limited functionality as e.g. pictures to pages can't be added via local UI. At least I didn't found out how.

### How to Reproduce

1. Login to Web ui
2. Navigate to profiles
3. Try to click on one of the two shown empty ones

### Expected behavior

Only my created profile(s) should appear and if I click on them, they should be opened to customize them.

### System version

RemoteTwo v1.3.3, Dock v 0.9.2

### What part of the system affected by the problem?

Core, Web Configurator

**Comment by kennymc-c** [comment] 2023-10-08 13:09
I also noticed this issue from time to time but only in Safari on macOS and not in Chrome so far. The workaround for me was to reload the page.

Maybe this console log will help the developers to track down the issue:

![User Interface Component Error_Console](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/14995555/5e4094fa-6b8d-4fcc-b2fc-d68e74decda5)

**Comment by zehnm** [comment] 2023-10-09 14:58
This is a known issue and will be fixed in a future update.

Workaround: manually reload the page, or close & reopen browser.

Caused by: after login the profiles are sometimes not reloaded and invalid data is shown. Clicking on one of the two empty profiles will not work, since the profile identifier is missing.

**Comment by zehnm** [comment] 2023-10-31 18:14
This _should_ be fixed in the next release, we are testing a fix and trying to reproduce this issue.

**Comment by zehnm** [comment] 2023-11-03 09:13
Closing: _should_ be fixed in release 1.4.5
Please reopen this issue if you still encounter it.

**Closed as completed by zehnm** 2023-11-03 09:13 UTC
Labels: bug, web configurator

**Comment by kennymc-c** [comment] 2023-11-03 17:40
Unfortunately, this still occurs with 1.4.5

**Comment by Depechie** [comment] 2023-11-05 10:36
Yep can also confirm I have the same issue still with 1.4.5
