### ISSUE TITLE
[bug] Slash (/) is allowed as Button name, but the custom button will not save when you use one.

### ISSUE THREAD

**Issue by kaandorp** [unfoldedcircle/bug-reports#86] opened 2023-09-27 15:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you create a custom button in the IR data set you can only use a certain type of characters. If you use a space for example you will get an error message and a text turns red. However, if you use a slash in the name, you can go ahead and learn the new commands. But there is actually no way to save it because of the slash in the name.

### How to Reproduce

Learn a new IR command.
For button name use something like "InputCbl/Sat"
Click Add Custom button
Learn the button
Click save. Nothing happens.

### Expected behavior

If the slash is not an allowed character it should behave the same as with a space. It would even be better to add a tooltip or message. Now the red text only suggests that it's incorrect.

### System version

1.2.1.

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment] 2023-09-27 15:19
Closing: 
- duplicate of #55 

A fix is in the works!

**Closed as completed by zehnm** 2023-09-27 15:19 UTC
Labels: bug, duplicate, web configurator

**Comment by mahnkej** [comment] 2023-10-02 17:48
Thx for fixing
