### ISSUE TITLE
Roon Extension appears inconsistently; unreliable and unusable

### ISSUE THREAD

**Issue by dnanian** [unfoldedcircle/bug-reports#215] opened 2023-12-01 18:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Although I'm using v1.4.8, where this is supposedly fixed, I'm unable to use the Roon integration.

Basically, the extension appears in Roon only intermittently. It'll work for the mere seconds it's available, then it vanishes and won't work... it comes back only occasionally.

### How to Reproduce

1. Enable integration
2. Add devices
3. Note that the extension in Roon disappears often (and may not come back)

### Expected behavior

Reliable operation and good integration

### System version

1.4.8

### What part of the system affected by the problem?

Integration

### Additional context

[UCR2_logs_2023-12-01.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13530742/UCR2_logs_2023-12-01.txt)

**Comment by zehnm** [comment] 2023-12-13 14:23
The next release contains a fix for a crash if zones changed, but nothing is playing.
The restarting of the integration causes the extension to disappear.

Also while the remote is sleeping, it will disappear from the Roon extensions.

**Comment by dnanian** [comment] 2023-12-13 14:41
That's not what seems to be going on here. I can't keep the extension up after a few minutes regardless. I do understand that if the remote is sleeping it won't appear - in my case, the remote is awake and fails to reactivate Roon over and over...

**Comment by zehnm** [comment] 2023-12-13 15:30
According to your logs the next release should fix it. But I'll double check.

**Comment by dnanian** [comment] 2023-12-13 15:37
OK! Note that I'm having similar weird stability problems with the B&O Integration, which I think I submitted separately.

**Comment by zehnm** [comment] 2023-12-15 07:33
The crash seen in your logfile is fixed in the v1.5.2 update.
@dnanian I hope this improves it for you. Please report back, if you still see this issue. 

I've got a Roon subscription now as well and can help testing and improving the integration. I wasn't able to reproduce the reported crash in the logs anymore. However, I've already noticed a few other things to improve like handling (large) album art images, which sometimes make the integration unavailable for a few seconds.
Handling disappearing audio outputs in Roon (zones) is another issue. In this case, the media-player entity should be shown as unavailable. This might also be an issue in my setup, since I'm using an USB DAC connected to a docking station. Probably not a preferred setup, but a good test case :-)

**Comment by dnanian** [comment] 2023-12-15 13:26
Looking at the Extensions tab in Roon now it seems more stable - they're there post-update (I had it on automatic). We'll see how it goes. Thanks!

**Comment by zehnm** [comment] 2024-01-09 20:03
Version 1.6.0 contains an improved zone subscription logic. Album art image logging has been disabled to prevent short freezes in the integration connectivity.
Please open a new issue if you still experience issues.

**Closed as completed by zehnm** 2024-01-09 20:03 UTC
Labels: bug, integration
