### ISSUE TITLE
Home Assistant "input_button" entity type (simple button) not working

### ISSUE THREAD

**Issue by sanderdw** [unfoldedcircle/bug-reports#13] opened 2023-09-04 07:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It seems that the "input_button" entity type (simple button) of home assistant is not compatible.

### How to Reproduce

Select a"input_button" entity type from the Home Assistant integration and try to map it to a button.

### Expected behavior

Something like this https://github.com/unfoldedcircle/core-api/blob/main/doc/entities/entity_button.md

### System version

v.1.0.5

### What part of the system affected by the problem?

Overall system

### Additional context

![image](https://github.com/unfoldedcircle/bug-reports/assets/19476345/b54a7ba9-51bd-4246-945c-39f8563575eb)

**Comment by zehnm** [comment] 2023-09-04 08:07
Please provide your Home Assistant version, and if possible the input button entity:
```console
curl --location 'http://$IP/api/entities/$ENTITY_ID' -u 'web-configurator:$PIN'
```
- $IP: ip or hostname of your remote
- $ENTITY_ID: identifier of the input button entity. Visible in Integrations, Home Assistant, Configured entities: edit -> below header line.
  e.g. `hass.main.button.my_input`
- $PIN: web-configurator pin

**Comment by sanderdw** [comment] 2023-09-04 08:16
Home assistant version:
`Home Assistant 2023.8.4
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest`
Result curl:
`{"entity_id":"hass.main.input_button.hdmi_nintento_button","entity_type":"button","integration_id":"hass.main","name":{"en":"HDMI Nintento Button"},"features":[],"attributes":{"state":"UNKNOWN"},"enabled":true}`

**Comment by sanderdw** [comment] 2023-09-04 08:26
I did another test with a button provided as part of a integration. I saw that my Unify protect integration provided a button entity and when adding this works ok.

Strange thing is the curl command result on this button is not really different:

`{"entity_id":"hass.main.button.bel_woonkamer_play_chime","entity_type":"button","integration_id":"hass.main","name":{"en":"Bel Woonkamer Play Chime"},"features":[],"attributes":{"state":"UNKNOWN"},"enabled":true}`

**Comment by zehnm** [comment] 2023-09-04 08:27
Thanks, I'll test it. The input helper button is a good hint and as far as I remember I haven't used it in my setup yet. This could very well be the issue :-)

**Comment by zehnm** [comment] 2023-09-06 12:35
Update: I could add some input button helpers to my HA installation and can reproduce the issues in the web-configurator. We are investigating :-) Looks like the button entity support is missing, since it's not even showing up in the available sequence commands...
Using an input_button in a profile page works and the button press is reported to HA.

**Comment by pri-me** [comment] 2023-09-16 12:04
Hi guys, I have the exact same problem. I am using the Philips TV integration in HA (https://www.home-assistant.io/integrations/philips_js/#remote) which exposes a remote entity. So I want to create `input_button` helpers for the various remote entity commands in order to assign them in an activity.   
Since this is IP-based, I assume it to have less latency than IR.

PS: Will it be possible to add a HA remote enitity to the "Remotes" section in the web configurator (or from any integration for that matter -> abstraction)? Otherwise it should be called "IR Remotes" :)

**Comment by zehnm** [comment] 2023-09-23 13:41
Closing: Home Assistant input_button has been added in 1.2.0. Note: scripts can only be triggered at the moment and parameters are not supported.

@pri-me It is in the backlog. Please create a feature request for HA remote entities to better track it. If it's a highly request feature, it will move up in the backlog :-)
Either directly in the [HA integration repo](https://github.com/unfoldedcircle/integration-home-assistant/issues), or here.

**Closed by zehnm** 2023-09-23 13:41 UTC
Labels: bug, system
