### ISSUE TITLE
[bug] Empty download logs from / with boot-id dropdown menus

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/bug-reports#141] opened 2023-10-20 13:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

From time to time it happens that the "Download logs from" and "with boot-id" dropdown menus inside the log settings menu are just showing one or multiple "Select all" entries. Additional Select all entries appear when close and reopen the window. When you click on Select all the browser tab freezes. When you click on Download you just get the core service logs. 
The current workaround is to reload the page to see all entries again.

![Bildschirmfoto 2023-10-20 um 15 07 01](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/14995555/5b2526e8-ec98-4592-8f7f-93d6c51e3e7f)

### How to Reproduce

1. Open the Web Configurator
2. Go to Settings/Logs
3. Open the Download logs from and with boot-id dropdown menu

### Expected behavior

The dropdown menu should show all services and boot-ids

### System version

1.4.3

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment] 2023-10-30 13:02
We couldn't reproduce this, but found the likely cause of it. _Fixed_ in next release.

**Comment by zehnm** [comment] 2023-11-03 09:13
Closing: _should_ be fixed in release 1.4.5
Otherwise, please reopen this issue.

**Closed as completed by zehnm** 2023-11-03 09:13 UTC
Labels: bug, web configurator

**Comment by kennymc-c** [comment] 2023-11-03 18:10
This issue still happens with 1.4.5
