### ISSUE TITLE
[bug] PoolTimedOut flooding logs

### ISSUE THREAD

**Issue by Snuffy2** [unfoldedcircle/bug-reports#154] opened 2023-10-28 15:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm not sure what is causing this, but my logs are currently flooded with PoolTimedOut errors. Not sure what is causing this. I have the Home Assistant integration, Apple TV integration and several IR devices setup.

[UCR2_logs_2023-10-28(1).txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13196184/UCR2_logs_2023-10-28.1.txt)

### How to Reproduce

See logs

### Expected behavior

Not to see this in the logs

### System version

1.4.3

### What part of the system affected by the problem?

Core

**Comment by zehnm** [comment] 2023-11-07 20:42
Did you experience this error again after a reboot?
If yes: can you somehow trigger it?

**Comment by zehnm** [comment] 2024-01-15 20:32
Closing: no further feedback received and not able to reproduce. Please reopen the issue if it happens again.

**Closed as not planned by zehnm** 2024-01-15 20:32 UTC
Labels: bug, core
