### ISSUE TITLE
[bug] Sony Android TV Integration - Power On Off

### ISSUE THREAD

**Issue by DennisFre** [unfoldedcircle/bug-reports#218] opened 2023-12-06 16:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If I add a Android TV Integration im not able to discrete turn on and off the TV. It is just every time a on/off toggle. 

### How to Reproduce

1. Add Android TV Integration 
2. Press Power On -> TV Turns On
3. Press Power On -> TV Turns Off 

### Expected behavior

1. Add Android TV Integration 
2. Press Power On -> TV Turns On
3. Press Power On -> TV stays On 

### System version

1.4.8

### What part of the system affected by the problem?

Integration

**Comment by splattner** [comment] 2024-01-17 16:54
I guess the problem is not the remote but the android tv remote protocol. The python library used by the intergration only support a power (toggle) [KEYCODE_POWER](https://github.com/tronikos/androidtvremote2/blob/main/src/androidtvremote2/remotemessage_pb2.pyi#L103) 
[here](https://github.com/unfoldedcircle/integration-androidtv/blob/main/intg-androidtv/tv.py#L48) we see that this command is used.

Maybee  [KEYCODE_SLEEP](https://github.com/tronikos/androidtvremote2/blob/main/src/androidtvremote2/remotemessage_pb2.pyi#L654) and [KEYCODE_WAKEUP](https://github.com/tronikos/androidtvremote2/blob/main/src/androidtvremote2/remotemessage_pb2.pyi#L659) would be the better choice?

**Comment by uvjim** [comment] 2024-02-08 21:40
Also seeing the issue and think it might be causing some weirdness in activity groups but I'm yet to try and get to the root cause of that.

**Comment by kennymc-c** [comment] 2024-02-09 17:46
When I still had a Sony Android TV (XE9005) I had no problems powering it on and off via the Android TV integration. Maybe it's a network or setting issue? Or just newer Android TV versions have this problem as my TV was from 2017 running Android TV 9.

**Comment by uvjim** [comment] 2024-02-09 18:02
I don't think my issue is related to the power toggling rather than being discrete. I did a quick check in the code and it appears to rely on the imported package telling it the state rather than calculating it itself.

I haven't had a chance to look any further, however having discrete power options would be easier when trying to fix things if they get out of sync in some way.

**Comment by zehnm** [comment] 2024-04-01 16:30
The current power state is now considered before sending the power toggle command. 
Unfortunately the Android TV remote protocol only defines a power toggle command. Other commands like SLEEP and WAKEUP don't work on every device. With the newly introduced device profiles and the keycode testing function, we can create device specific profiles where this commands are supported.

The new Android TV integration version will soon be released in beta channel.

**Comment by zehnm** [comment] 2024-04-01 21:18
Included in the just released beta firmware 1.7.9 and will be part of the next public release.

**Comment by zehnm** [comment] 2024-05-16 15:19
Fixed in release 1.7.12

**Closed as completed by zehnm** 2024-05-16 15:19 UTC
Labels: bug, integration
