### ISSUE TITLE
[bug] Roon integration reports "uc_roon_driver session not available"

### ISSUE THREAD

**Issue by conrad-nash** [unfoldedcircle/bug-reports#109] opened 2023-10-07 18:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I've set up a Roon integration on my remote 2. Immediately after setting up the integration the control from the remote works well. I'm able to play, pause, skip, change volume etc. and the artwork shows.

At some point after that the connection breaks. When I try and perform any action against the integration on the remote I get the error message bar with "uc_roon_driver session not available".

I've rebooted the remote and it continues to be broken

If I remove and re-add the integration it seems to work.

### How to Reproduce

1. Add Roon integration, confirm working
2. Wait
3. try and interact with an existing integration and see the error
(sorry, that's not super helpful!)

### Expected behavior

I expect previous roon sessions to be available for as long as the roon playback device is available.

### System version

1.3.3

### What part of the system affected by the problem?

Integration

### Additional context

[UCR2_logs_2023-10-07 (1).txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/12838524/UCR2_logs_2023-10-07.1.txt)

Here's a log file that shows errors in it.

**Comment by jorritdb** [comment] 2023-11-04 18:32
+1

Same problem here. Roon intergration works for a moment and then it just stops. 
In Roon I can see the extention going on and than disappears

**Comment by quintz** [comment] 2023-11-11 22:33
+1 
Same for me.
I saw the extension popping up for a second in Roon and then disappear.
Seems the connector to the roon server crashes..

**Comment by HydrologyIRE** [comment] 2023-11-12 10:44
Same issue here with this meesage in Web Config:-
Driver not connected. Failed to connect to host: Connection refused (os error 111)

**Comment by RC-Thoughts** [comment] 2023-11-13 20:41
+1

Also the extension in Roon is coming and going until it stops showing all together (timeout?)

**Comment by zehnm** [comment] 2023-11-13 20:58
Please upload the "Roon integration" logs with priority `DEBUG`. The provided logs show connection refused errors, which indicates that the Roon integration is no longer running. The Roon logs should tell us what's wrong.

**Comment by HydrologyIRE** [comment] 2023-11-13 23:13
[UCR2_logs_2023-11-13.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13342872/UCR2_logs_2023-11-13.txt)

**Comment by RC-Thoughts** [comment] 2023-11-14 10:30
I deleted Roon-integration and rebooted Remote Two, added Roon and within minute it stopped working. Time was around 2023-11-14 10:20. 

[Roon_Issue_001_UCR2_logs_2023-11-14.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13347600/Roon_Issue_001_UCR2_logs_2023-11-14.txt)

**Comment by zehnm** [comment] 2023-11-14 12:12
@HydrologyIRE thanks for the logs and I see the cause of the issue in the log. We start fixing it!

@RC-Thoughts your logfile only shows the "Core service" logs, we require the "Roon integration" logs with priority "DEBUG":
<img width="544" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/17356629/3509d99f-0294-4ef9-9539-04c6b01b76e6">

 Most likely you face the same Roon issue I found in the other log file, but it would be great if you could provide your logs as well. Just to make sure it's the same issue.

**Comment by RC-Thoughts** [comment] 2023-11-14 12:23
@zehnm  Sorry, my bad. But to my defense the drop down was empty before :) Looks like web-gui needs some forced refreshes every now and then.

[Roon_Issue_002_UCR2_logs_2023-11-14.txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13348637/Roon_Issue_002_UCR2_logs_2023-11-14.txt)

**Comment by zehnm** [comment] 2023-11-14 12:33
@RC-Thoughts thanks! I can confirm that it's the same issue

**Comment by conrad-nash** [comment] 2023-11-14 13:30
Here's mine as well.

[UCR2_logs_2023-11-14 (2).txt](https://github.com/unfoldedcircle/feature-and-bug-tracker/files/13349284/UCR2_logs_2023-11-14.2.txt)

Thanks.

**Comment by zehnm** [comment] 2023-11-15 20:16
Status: fix is released in the BETA group and available later this week if we don't find any showstopper.

**Comment by RC-Thoughts** [comment] 2023-11-19 08:12
@zehnm Any news?

**Comment by zehnm** [comment] 2023-11-19 13:59
Roon integration is updated in the just released v1.4.8 update.
This should fix the reported issues. We couldn't reproduce it anymore with our test system.
If you still experience issues, please re-open this ticket or create a new one and add the  "Roon integration" logs.

**Closed as completed by zehnm** 2023-11-19 13:59 UTC
Labels: bug, integration
