### ISSUE TITLE
[bug] Dock LED brightness bug has *not* been fixed

### ISSUE THREAD

**Issue by spl237** [unfoldedcircle/bug-reports#304] opened 2024-01-31 20:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/178 - this bug is *not* fixed in the 1.6.7 release.

If I change the dock LED brightness in either the remote or the web configurator, wait for the "change has been saved" message, leave the dock screen and come back, the LED brightness has reverted to the original value.

This bug is not - I repeat not - fixed for me.

### How to Reproduce

1. Go to dock settings in either remote or web configurator
2. Change LED brightness
3. Wait for "change saved" message
4. Leave dock settings
5. Return to dock settings
6. Observe value did not actually change

### Expected behavior

The LED brightness should be saved, not just thrown away.

### System version

1.6.7

### What part of the system affected by the problem?

Web Configurator, Overall system

**Comment by Quinterly** [comment] 2024-02-01 02:06
Not fixed for me either.

**Comment by zehnm** [comment] 2024-02-01 09:05
Confirmed: display issue in the web-configurator & remote-ui.
The new Brightness value is saved but the old value is displayed when the dialog is reopened.
Workaround for web-configurator: refresh the page.

**Comment by spl237** [comment] 2024-02-01 09:08
It's not just the displayed value which is wrong.

I cannot set the LED brightness to zero - nothing I have tried works. It always reverts to the previous value, and the LEDs keep coming on.

**Comment by Quinterly** [comment] 2024-02-02 16:18
> It's not just the displayed value which is wrong.
> 
> I cannot set the LED brightness to zero - nothing I have tried works. It always reverts to the previous value, and the LEDs keep coming on.

This is the issue. It's not the configurator, it's that the brightness is not controlled by the configuration.

**Comment by henrikwidlund** [comment] 2024-02-04 14:29
> It's not just the displayed value which is wrong.
> 
> 
> 
> I cannot set the LED brightness to zero - nothing I have tried works. It always reverts to the previous value, and the LEDs keep coming on.

For me it works from then web ui. Changing from the remote doesn't allow for setting to 0. Last time I tried it on the remote it displayed as 10% in the web ui after the change.

**Comment by zehnm** [comment] 2024-02-06 18:14
> This is the issue. It's not the configurator, it's that the brightness is not controlled by the configuration.

See #51. It's a "feature" that certain LED notifications are still shown. A "full-off" mode will be added.

Closing this ticket since the invalid dock brightness value in the web-configurator has been fixed in 1.6.9
The configuration in remote-ui will be fixed in a future update.

**Closed as completed by zehnm** 2024-02-06 18:14 UTC
Labels: bug, system, web configurator
