### ISSUE TITLE
[bug] Macros don't run automatically if they are called from outside of an activity

### ISSUE THREAD

**Issue by hprotter** [unfoldedcircle/bug-reports#177] opened 2023-11-06 14:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A macro that is called from a home page (outside an activity) will not run automatically from start to end. Instead it shows every command of the macro and wait for a key press with a big square button on the display. The last command in the macro will not executed and show up again each time you press the button. 

### How to Reproduce

1. Implement a macro on a home page (e.g. 'Living-Room')
2. Call the macro
3. The macro will not automatically run from start to end, instead each command of the macro will wait for a button press/tap

### Expected behavior

A macro that is called from a home page should run automatically from start to end and should finished automatically at the end.

### System version

v1.4.5

**Comment by zehnm** [comment] 2023-12-18 20:23
Closing: I can't reproduce this with the current version. Macro runs automatically from start to end. 
- If the entity screen is opened (long press*, or tap on macro text) a push button is shown. Pressing it will run the entire command and the macro screen with the button remains open.
- If macro is run directly (short press*, or tap on macro icon) the macro is directly run.

\* This depends on settings -> user interface -> inverted button behaviour.

**Closed as completed by zehnm** 2023-12-18 20:23 UTC
Labels: bug
