### ISSUE TITLE
[feature request] Fire IR commands from Home Assistant

### ISSUE THREAD

**Issue by ascoarchitect** [unfoldedcircle/bug-reports#156] opened 2023-10-29 10:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Apologies if this has been requested and I just couldn't find it in the list - I'm trying to find way to easily fire IR commands from my Remote Two for integrations configured on the remote (essentially the reverse of a standard HASS integration). I've setup a Samsung IR integration on the device, and want to call the 'back' button using IR (for example). 
Ideally RemoteTwo to make entities available to HASS for each IR configured device.

**Comment by zehnm** [comment] 2023-10-30 16:37
Duplicate of #114 
See my comment on how you can integrate the dock into Home Assistant for sending IR codes (not the defined remote-devices in Remote Two, but for sending PRONTO codes, without the R2 being online).

**Closed as completed by zehnm** 2023-10-30 16:37 UTC
Labels: duplicate, feature request
