### ISSUE TITLE
[Power from home assistant, execute, close, know status of remote control activities request] title

### ISSUE THREAD

**Issue by neo2angel** [unfoldedcircle/bug-reports#123] opened 2023-10-11 13:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

That from home assistant, you can know the status of a certain activity, whether it is being executed or not... and also, that you can execute an activity or close it if it is running, and that all this is updated on the command .

For example, if I am running "watch television" from home assistant, the activity can be closed and the controller returns to the origin screen, and the activity appears as "off" on the controller.

**Comment by martonborzak** [comment] 2023-10-11 13:53
Duplicate of #114

**Closed as completed by martonborzak** 2023-10-11 13:53 UTC
Labels: feature request
