### ISSUE TITLE
Upload new Icons/Images: WebConfigurator UI freezes

### ISSUE THREAD

**Issue by alexthegreat100** [unfoldedcircle/bug-reports#232] opened 2023-12-18 16:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If a file is uploaded in the upload dialogue for icons and images that does not correspond to the dimensions 90x90 px for icons or 275 x 480 px for background images (or in the correct file format), the UI freezes.
The same happens if you accidentally click on "Upload" without first selecting a file or if you try to upload a file with an identical name (duplicate). 
The only thing that helps is to reload the page.

### How to Reproduce

1. Go to "Settings"
2. Click on "Ressources"
3. Click on "Upload"
4. Try to upload a file with wrong size or format
5. Try to upload a duplicate (same file name)
6. Click on "Upload" without selecting a file

### Expected behavior

Intercept unaccepted resolutions for icons and images, duplicates and "no selection" and show a pop-up window with a warning and a "back" button. 

### System version

v1.5.2

### What part of the system affected by the problem?

Web Configurator

**Comment by uvjim** [comment] 2023-12-20 14:13
Also seeing this.  Eventually the tab crashes and you need to reload anyway.

**Comment by zehnm** [comment] 2023-12-20 14:15
This is definitely a bug in the web-configurator and will be fixed. It receives a bad request about the malformed image, but then crashes instead of displaying the error.

**Comment by loekf** [comment] 2023-12-24 18:07
I also see the following:
If you try to upload an icon with the same name, the Web Configuration freezes as well. Closing the tab in the browser is the only way to fix this (then login in again).

Furthermore, there is no way to remove downloaded icons, like you can with backgrounds. There is no red cross.

Update: you can still remove them under Resources. Guess an inconsistency in the UI.

**Comment by zehnm** [comment] 2023-12-27 09:49
This is the same issue, as soon as an error is returned from the backend, the web-configurator freezes during image upload.

**Comment by loekf** [comment] 2023-12-27 10:20
Sometimes things recover after a reload, but the only fix I have found is rebooting the remote.

**Comment by zehnm** [comment] 2023-12-27 12:47
Closing the web browser (tab) is enough, rebooting is not required.

**Comment by loekf** [comment] 2023-12-27 12:56
I found out it was related to a (looks like it) corrupt PNG file with a strange canvas containing not visble pixels in e.g. macOS Preview, but are visible in Affinity Photo 2. Could also be caused by a corrupt SVG file, which was the original source.

**Comment by zehnm** [comment] 2024-01-09 19:58
Fixed in 1.6.0

**Closed as completed by zehnm** 2024-01-09 19:58 UTC
Labels: bug, web configurator
