### ISSUE TITLE
[bug] tv icons category not used when designing pages

### ISSUE THREAD

**Issue by loekf** [unfoldedcircle/bug-reports#248] opened 2023-12-26 21:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not sure why there are icons, custom icons and tv icons. They are all three visible under resources, but if you are designing the layout of a page and want to add icons for tv channels, all there is are icons and custom icons.

So the seperate category tv icons is useless.

### How to Reproduce

Check resources
Add a page for an activity, add an icon element and try to change the icon picture

### Expected behavior

Remove tv icon category, unless there us a use for it.

### System version

1.5.2

### What part of the system affected by the problem?

Web Configurator

**Comment by zehnm** [comment] 2023-12-27 12:39
Closing: duplicate of #233

**Closed as completed by zehnm** 2023-12-27 12:39 UTC
Labels: bug, duplicate, web configurator
