### ISSUE TITLE
Problem with firmware version 1.6.9 and starting/stopping of activities

### ISSUE THREAD

**Issue by hprotter** [unfoldedcircle/bug-reports#312] opened 2024-02-07 08:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

With the latest firmware update 1.6.9, I have the problem that when starting an activity, the display of the steps of the start sequence stops at the last step, continues to be displayed and thus the UI of the activity is not displayed. To fix this, I have to exit the activity and start it again. The same happens when exiting an activity when the off sequence is run through.

### How to Reproduce

Install firmware version 1.6.9 
Start an activity. 
In display the steps of the start sequence are shown. 
The last step of the start sequence will not disappear from display and UI of that activity will not be shown. 
Exit the activity and start it again. 
UI of the activity will be shown. 

End an activity. 
The last step of the off sequence will be shown on the display and will not disappear from display. 
Exit the activity. 
Home display is shown. 

### Expected behavior

After start of an activity the UI of the activity should appear. 
After end of an activity the home display should appear.

### System version

1.6.9

### What part of the system affected by the problem?

UI

**Comment by martonborzak** [comment] 2024-02-07 08:34
Duplicate of #311

**Closed as completed by martonborzak** 2024-02-07 08:34 UTC
Labels: bug, ui
