### ISSUE TITLE
[bug] New Web Configurator - Unable to edit soft buttons

### ISSUE THREAD

**Issue by uvjim** [unfoldedcircle/bug-reports#414] opened 2024-12-11 20:37 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I have just updated to version 2.2.0 which has the new Web Configurator.  I am now unable to edit any soft buttons which use a custom icon.

### How to Reproduce

1. Create a button with an icon.
2. Select a custom icon.
3. Assign the necessary commands.
4. Close the dialog.
5. Attempt to edit the button.

### Expected behavior

To be able to edit the button configuration.

### System version

2.2.0

### What part of the system affected by the problem?

Web Configurator

### Additional context

https://github.com/user-attachments/assets/0af59c23-0146-47a8-90fc-7a5f3e4b8c4b

**Comment by kennymc-c** [comment] 2024-12-11 23:35
I can confirm this bug too.
Also, custom icons that have been cropped with the build in tool are shown in a circle shape instead of a rectangle like in the icons menu and there are also some scaling artefacts
<img width="182" alt="Image" src="https://github.com/user-attachments/assets/a68c4bac-424d-421b-b0c9-20c18d99e413" />


If you change the size of the button this can even result in a some weird glitches where the icon is bigger than the actual button grid cell. But I couldn't reproduce this glitch a seconds time. But the shape is still a circle

Edit: I was able to reproduce the glitch, even with a matching 90x90 icon:

https://github.com/user-attachments/assets/e743266e-06af-4d93-9e39-fdb60003ef54

**Comment by uvjim** [comment] 2024-12-12 07:39
I have found that if I open the browser Developer Tools and inspect the button element, i can get to the edit functionality by changing `z-index` on the edit span and bringing it forwards.

**Comment by martonborzak** [comment] 2024-12-13 19:56
Fixed in 2.2.1.

**Closed as completed by martonborzak** 2024-12-13 19:56 UTC
Labels: bug, web configurator

**Comment by kennymc-c** [comment] 2024-12-13 20:11
@martonborzak The additional bugs from my comment are still there with 2.2.1

**Comment by uvjim** [comment] 2024-12-13 21:16
@martonborzak confirmed fixed for the issue I raised.
